# Generated by Django 4.1.2 on 2022-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_project', models.CharField(max_length=100)),
                ('size_project', models.SmallIntegerField()),
                ('company', models.CharField(max_length=100)),
                ('dates', models.DateTimeField(blank=True, null=True)),
                ('value', models.SmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('room', models.SmallIntegerField()),
                ('floor', models.SmallIntegerField()),
                ('property_type', models.CharField(max_length=100)),
                ('square_meter', models.SmallIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
