# Generated by Django 4.1.3 on 2022-11-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_project_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='_id',
            new_name='id',
        ),
    ]
