# Generated by Django 4.1.3 on 2022-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_project_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='street_number',
            field=models.SmallIntegerField(verbose_name='street_number'),
        ),
    ]
